#!/usr/bin/env python

# standard library
import os

def build(bld):

    os.chdir(bld.env.project_paths['GRM_ESTIMATOR'] + '/tests')

    bld(features = 'run_py_script', source = 'testEstRuns.py', target = '',  version = 2)
